<?php

namespace App\Shared\Constants;

/**
 * TestCredentials - Fixed test credentials for E2E tests
 *
 * These are known, hardcoded test credentials used during development and testing.
 * They are NOT secrets - they are public test values that change never.
 * Real production credentials are never hardcoded.
 *
 * Usage:
 * - Database seeders use these to create test data deterministically
 * - E2E test fixtures use these to authenticate without env vars
 * - Tests are reproducible and don't depend on external configuration
 *
 * Security: These are test-only values. Real production uses:
 * - Strong random admin passwords (set manually)
 * - Terminal tokens generated by seeder (one-time use, stored as hash)
 */
final class TestCredentials
{
    /**
     * Admin user for testing
     * Email: admin@example.com
     * Password: password123
     *
     * This is created by AdminUsersSeeder
     */
    public const ADMIN_EMAIL = 'admin@example.com';
    public const ADMIN_PASSWORD = 'password123';

    /**
     * Terminal API token for testing
     * Used by E2E tests to make authenticated requests
     *
     * This token is hashed and stored in the database by TerminalSeeder.
     * Tests use the plaintext token to authenticate.
     *
     * Format: Fixed deterministic string (not random)
     * Length: 64 chars (same as real tokens for consistency)
     */
    public const TERMINAL_TOKEN = 'test-terminal-token-do-not-use-in-production-0a1b2c3d4e5f6g7h';

    /**
     * Terminal device ID for testing
     * Used to identify the test terminal in logs and database
     */
    public const TERMINAL_DEVICE_ID = 'test-device-001';

    /**
     * Terminal name for testing
     */
    public const TERMINAL_NAME = 'Test Terminal';
}
