<?php

declare(strict_types=1);

namespace App\Modules\Notifications\Mail;

use App\Modules\Notifications\DTOs\TerminalTokenIssuedDataDto;
use App\Shared\Mail\MailLayout;
use App\Shared\Mail\MailMessage;

/**
 * "A terminal credential was issued" (ADR-0043).
 *
 * The counterpart to {@see CredentialExpiryMail}: that one is sent because a
 * secret is running out, this one because a secret was created. Both are
 * addressed to every active admin, and this one is addressed to the acting
 * admin too — a receipt they can ignore, whose value is that they will have
 * seen one before the day somebody else mints a credential in their name.
 *
 * Three things it does on purpose.
 *
 * **It asks a question rather than reporting a fact.** "Terminal X was
 * credentialled at 14:05" is a log line; "if this was not you or a colleague,
 * revoke it" is something a reader can act on. The recovery instruction is
 * named the way the panel labels it, because a message that says *act* and
 * leaves the reader hunting for the button gets closed instead.
 *
 * **It carries no token material** — not the token, not its hash, not a prefix.
 * The message is generated by the creation of a secret, so the one thing it
 * must never do is distribute it. It says so out loud, for the reason
 * {@see CredentialExpiryMail} does: mail about credentials is exactly the shape
 * phishing imitates, and a reader who knows these messages never contain a
 * token has a rule to apply to the one that does.
 *
 * **It does not name who did it.** See {@see TerminalTokenIssuedDataDto} — the
 * actor is not recoverable at send time without guessing, and a security notice
 * that names the wrong colleague is worse than one that names none. It points
 * at the audit log, which is exact.
 */
final class TerminalTokenIssuedMail
{
    public static function render(TerminalTokenIssuedDataDto $data): MailMessage
    {
        $t = new MailStrings($data->language);

        $subject = $t->t('terminal_token_issued.subject.' . $data->event, [
            'name' => $data->terminalName,
        ]);

        // A blank value drops its whole line rather than printing a label with
        // nothing after it. Both dated fields can legitimately be missing — the
        // credential this announces may have been revoked or superseded between
        // enqueue and drain, and a hand-edited row may carry no issuance stamp
        // at all — and a security notice with an empty "valid until" reads as a
        // system that has lost track of the credential it is warning about.
        $rows = array_filter([
            $t->t('terminal_token_issued.label_terminal') => $data->terminalName,
            $t->t('terminal_token_issued.label_device')   => $data->deviceId,
            $t->t('terminal_token_issued.label_event')    => $t->t('terminal_token_issued.event.' . $data->event),
            $t->t('terminal_token_issued.label_issued')   => $data->issuedOn,
            $t->t('terminal_token_issued.label_expires')  => $data->expiresOn,
        ], static fn(string $value): bool => trim($value) !== '');

        $html = MailLayout::document($data->branding, [
            'title' => $subject,
            'preview' => $t->t('terminal_token_issued.preheader', [
                'name' => $data->terminalName,
                'moment' => $data->issuedOn,
            ]),
            'lang' => $data->language->value,
            'content' => self::html($t, $data, $rows),
            'trailer' => $t->t('automated_note'),
        ]);

        return new MailMessage(
            to: $data->recipientAddress,
            subject: $subject,
            html: $html,
            text: self::text($t, $data, $rows),
            toName: $data->recipientName,
        );
    }

    /** @param array<string,string> $rows */
    private static function html(MailStrings $t, TerminalTokenIssuedDataDto $data, array $rows): string
    {
        return MailLayout::contentStart()
            . MailLayout::eyebrow($t->t('terminal_token_issued.eyebrow'))
            . MailLayout::title($t->t('terminal_token_issued.title'))
            . MailLayout::paragraph(MailLayout::esc(MailTextBody::greeting($t, $data->recipientName)))
            . MailLayout::lede($t->t('terminal_token_issued.lede.' . $data->event, [
                'name' => MailLayout::esc($data->terminalName),
                'moment' => MailLayout::esc($data->issuedOn),
            ]))
            . MailLayout::dataTable($rows)
            . MailLayout::noteBox(
                $t->t('terminal_token_issued.action_heading'),
                MailLayout::paragraph(MailLayout::esc($t->t('terminal_token_issued.action'))),
            )
            . MailLayout::paragraph(MailLayout::esc($t->t('terminal_token_issued.why_everyone')))
            . MailLayout::paragraph(MailLayout::esc($t->t('terminal_token_issued.no_secret')))
            . MailLayout::signOff($t->t('signoff'), $data->branding->orgName)
            . MailLayout::contentEnd();
    }

    /** @param array<string,string> $rows */
    private static function text(MailStrings $t, TerminalTokenIssuedDataDto $data, array $rows): string
    {
        $lines = [
            MailTextBody::greeting($t, $data->recipientName),
            '',
            $t->t('terminal_token_issued.lede_text.' . $data->event, [
                'name' => $data->terminalName,
                'moment' => $data->issuedOn,
            ]),
            '',
        ];

        foreach ($rows as $label => $value) {
            $lines[] = $label . ': ' . $value;
        }

        $lines[] = '';
        $lines[] = $t->t('terminal_token_issued.action_heading');
        $lines[] = $t->t('terminal_token_issued.action');
        $lines[] = '';
        $lines[] = $t->t('terminal_token_issued.why_everyone');
        $lines[] = '';
        $lines[] = $t->t('terminal_token_issued.no_secret');

        return MailTextBody::finish($lines, $data->branding, $t);
    }
}
