-- The club's control over its own registration surface (#783, ADR-0052).
--
-- Four acts an admin takes on the surface itself rather than on a submission:
-- rotating the poster secret, switching registration on, switching it off with
-- a reason, and pointing at a different published Anmeldung.
--
-- Same ENUM caveat as migrations 060 and 061: a case in `AuditAction` with no
-- value here is refused by MariaDB at write time, and `AuditActionSchemaTest`
-- catches it in 0.2s instead of at runtime.

ALTER TABLE audit_log MODIFY COLUMN action ENUM(
    'create',
    'update',
    'delete',
    'anonymize',
    'login',
    'logout',
    'login_failed',
    'export',
    'settlement_create',
    'settlement_cancel',
    'settlement_export',
    'settlement_submit',
    'settlement_reverse',
    'transaction_storno',
    'transaction_price_divergence',
    'collection_hold_placed',
    'collection_hold_cleared',
    'activate',
    'deactivate',
    'reorder',
    'totp_enrolled',
    'totp_reset',
    'mandate_document_upload',
    'mandate_document_delete',
    'terminal_repair',
    'key_registered',
    'key_activated',
    'key_rotation_started',
    'key_rotation_batch_completed',
    'key_rotation_completed',
    'key_retired',
    'key_revoked',
    'key_marked_compromised',
    'sepa_export',
    'iban_full_view',
    'terminal_token_created',
    'terminal_token_activated',
    'terminal_token_rotated',
    'terminal_token_revoked',
    'terminal_token_expired',
    'mail_enqueued',
    'mail_superseded',
    'mail_retried',
    'mail_test_sent',
    'terminal_anomaly_detected',
    'terminal_anomaly_acknowledged',
    'cron_secret_rotated',
    'password_changed',
    'email_changed',
    'role_granted',
    'role_revoked',
    'jugendschutz_violation',
    'jugendschutz_violation_acknowledged',
    'invitation_sent',
    'invitation_accepted',
    'registration_approved',
    'registration_rejected',
    'registration_edited',
    'registration_printed',
    'registration_secret_rotated',
    'registration_enabled',
    'registration_disabled',
    'registration_document_url_changed'
) NOT NULL;
