targets:
  $default:
    sources:
      - lib/**
      - openapi/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "openapi/"
          output_folder: "lib/generated/"
          with_base_url: false
          classes_with_nullable_lists:
            - ".*"
          build_only_models: false
