#!/usr/bin/env node
/**
 * Says so when the pinned Flutter SDK falls behind the stable channel.
 *
 * Why: `FLUTTER_VERSION` in `.github/workflows/build.yaml` is the one input to
 * the terminal build that no update process tracks. Dependabot's `pub` entry
 * moves the packages (#649), OSV-Scanner reads `pubspec.lock` for advisories,
 * but the SDK that compiles the binary handed to a club is a plain string in a
 * workflow's `env:` block — and after #648 stopped it from cloning `stable`,
 * nothing ever moves it. A stale pin is quiet in two ways: it silently caps
 * which package versions can resolve (a Dependabot pull request then just
 * fails to `pub get`, with the cause on nobody's branch), and the lockfile's
 * `flutter: ">=x.y.z"` floor can walk past it on a bump, at which point CI is
 * red for a reason the diff does not show.
 *
 * What it does: reads the pin, reads the floor from `pubspec.lock`, asks
 * Flutter's own release feed what stable is, and keeps **one** issue in step
 * with the answer — opened when the pin lags, told once per new stable, closed
 * by the first run that finds the pin current. An issue rather than a pull
 * request, on purpose: the pin's own comment says to bump it deliberately and
 * read the release notes, because it is the input that changes what the
 * binary *is*. A bot cannot read release notes for you; it can make sure you
 * know there are some.
 *
 * Self-closing matters as much as opening (see scheduled-failure-issue.yaml):
 * an open issue here always means "behind right now".
 *
 * Runs weekly from `.github/workflows/flutter-sdk-lag.yaml`, on `main` after a
 * push that touches either input, and by hand. Imports nothing outside Node's
 * standard library and talks to GitHub through `gh`, like the merge queue —
 * a workflow with `issues: write` should not execute a dependency tree it
 * has not audited.
 */

import { execFileSync } from 'node:child_process'
import { appendFileSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..', '..')
export const BUILD_YAML = resolve(ROOT, '.github', 'workflows', 'build.yaml')
export const PUBSPEC_LOCK = resolve(ROOT, 'terminal-frontend', 'pubspec.lock')

/**
 * Flutter's own release feed. The `_linux` variant because that is what
 * `build-terminal` runs on; the stable version is the same on every platform.
 */
export const RELEASES_URL = 'https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json'

/** Exact title, so repeated runs find one issue instead of opening a new one. */
export const ISSUE_TITLE = 'Flutter SDK pin is behind stable'

/**
 * The labels a new issue carries. `ready-for-agent` rather than `owner-action`:
 * the bump itself is a one-line change plus a CI run, which an agent can do —
 * reading the release notes is the review, and that happens on its pull request.
 */
export const ISSUE_LABELS = ['dependencies', 'terminal-frontend', 'ready-for-agent', 'priority: low']

const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_'

/** Hidden marker so a run recognises what has already been said about a given stable. */
export const marker = (version) => `<!-- flutter-sdk-lag:${version} -->`

// ---------------------------------------------------------------------------
// Reading the inputs
// ---------------------------------------------------------------------------

const VERSION = /^\d+(\.\d+)*$/

/** `FLUTTER_VERSION: '3.47.1'` out of the workflow's `env:` block. */
export function pinnedVersion(buildYaml) {
  const match = /^\s*FLUTTER_VERSION:\s*['"]?([^'"\s#]+)['"]?\s*(#.*)?$/m.exec(buildYaml)
  if (!match) throw new Error('build.yaml declares no FLUTTER_VERSION')
  const version = match[1]
  if (!VERSION.test(version)) {
    throw new Error(`FLUTTER_VERSION is '${version}', which is not a version — a branch name pins nothing`)
  }
  return version
}

/**
 * The lower bound `pubspec.lock` records under `sdks:` — the floor the pin
 * must satisfy for `flutter pub get` to resolve at all. Null when the lockfile
 * states none.
 */
export function lockfileFloor(pubspecLock) {
  const block = /^sdks:\s*\n((?:[ \t]+.*\n?)*)/m.exec(pubspecLock)
  if (!block) return null
  const flutter = /^\s*flutter:\s*['"]?\s*>=\s*(\d+(?:\.\d+)*)/m.exec(block[1])
  return flutter ? flutter[1] : null
}

/**
 * The stable release the feed is pointing at. `current_release.stable` is a
 * hash, so it is looked up in `releases`; a feed without the pointer falls
 * back to the highest stable version. Never a beta, and never "nothing" — a
 * feed that names no stable release is an error, because reading it as
 * "current" is the silent failure this check exists to prevent.
 */
export function latestStable(feed) {
  const releases = (feed?.releases ?? []).filter((r) => r.channel === 'stable' && VERSION.test(r.version ?? ''))
  if (releases.length === 0) throw new Error('the release feed lists no stable release')

  const pointer = feed?.current_release?.stable
  const chosen =
    releases.find((r) => r.hash === pointer) ??
    releases.reduce((a, b) => (compareVersions(a.version, b.version) >= 0 ? a : b))

  return {
    version: chosen.version,
    releaseDate: chosen.release_date ?? null,
    dartSdkVersion: chosen.dart_sdk_version ?? null,
  }
}

// ---------------------------------------------------------------------------
// Versions
// ---------------------------------------------------------------------------

/** Numeric per dotted component; a missing component is 0, so 3.47 == 3.47.0. */
export function compareVersions(a, b) {
  const as = String(a).split('.').map(Number)
  const bs = String(b).split('.').map(Number)
  const length = Math.max(as.length, bs.length)
  for (let i = 0; i < length; i++) {
    const diff = (as[i] ?? 0) - (bs[i] ?? 0)
    if (diff !== 0) return diff
  }
  return 0
}

// ---------------------------------------------------------------------------
// The verdict
// ---------------------------------------------------------------------------

/**
 * @returns {{status: 'current'|'lagging'|'below-floor', pinned, latest, floor}}
 *
 * `below-floor` wins over `lagging`: a pin the lockfile refuses is not
 * "behind", it is a build that cannot resolve, and the issue has to say that.
 * A pin *ahead* of the feed is current — the feed can trail a fresh bump by a
 * day, and that is not a reason to open anything.
 */
export function assess({ pinned, latest, floor = null }) {
  const base = { pinned, latest, floor }
  if (floor && compareVersions(pinned, floor) < 0) return { ...base, status: 'below-floor' }
  if (compareVersions(pinned, latest.version) < 0) return { ...base, status: 'lagging' }
  return { ...base, status: 'current' }
}

// ---------------------------------------------------------------------------
// What the issue says
// ---------------------------------------------------------------------------

const releasedOn = (latest) => (latest.releaseDate ? ` (released ${String(latest.releaseDate).slice(0, 10)})` : '')

function stateLines(verdict) {
  const { pinned, latest, floor } = verdict
  return [
    `| | |`,
    `|---|---|`,
    `| Pinned (\`FLUTTER_VERSION\` in \`.github/workflows/build.yaml\`) | \`${pinned}\` |`,
    `| Latest stable | \`${latest.version}\`${releasedOn(latest)}${latest.dartSdkVersion ? `, Dart ${latest.dartSdkVersion}` : ''} |`,
    `| Floor (\`sdks.flutter\` in \`terminal-frontend/pubspec.lock\`) | ${floor ? `\`>=${floor}\`` : 'none'} |`,
  ].join('\n')
}

export function issueBody(verdict) {
  const { pinned, latest, floor } = verdict
  const lead =
    verdict.status === 'below-floor'
      ? `The pinned Flutter SDK \`${pinned}\` is **below** the \`>=${floor}\` floor that \`terminal-frontend/pubspec.lock\` ` +
        'records, so `flutter pub get` cannot resolve and `build-terminal` is red, or will be on the next run. ' +
        'This usually means a package bump moved the floor past the pin.'
      : `The Flutter SDK that compiles the terminal is pinned to \`${pinned}\`; the stable channel is at \`${latest.version}\`.`

  return (
    `${lead}\n\n` +
    `${stateLines(verdict)}\n\n` +
    '**To bump:** change `FLUTTER_VERSION` in `.github/workflows/build.yaml` in a pull request of its own, ' +
    'read the [release notes](https://docs.flutter.dev/release/release-notes) for what changed, and let ' +
    '`build-terminal` prove it: `flutter pub get`, `build_runner`, the unit and integration suites and ' +
    '`flutter build linux --release` all run on that pull request. The SDK cache key contains the version, so a ' +
    'bump re-clones deliberately.\n\n' +
    'The pin is not tracked by Dependabot — it is a value in a workflow `env:` block, not a dependency in any ' +
    'manifest — which is why this issue exists. It was opened by `.github/workflows/flutter-sdk-lag.yaml`, is ' +
    'told once per new stable release, and closes itself on the first run that finds the pin current, so an open ' +
    'one always means "behind right now".' +
    `\n\n${marker(latest.version)}${FOOTER}`
  )
}

function updateComment(verdict) {
  const { latest } = verdict
  const lead =
    verdict.status === 'below-floor'
      ? `The pin \`${verdict.pinned}\` is now **below** the lockfile floor \`>=${verdict.floor}\` as well.`
      : `Stable has moved on to \`${latest.version}\`${releasedOn(latest)}; the pin is still \`${verdict.pinned}\`.`
  return `${lead}\n\n${stateLines(verdict)}${FOOTER}`
}

function closingComment(verdict) {
  return `The pin is \`${verdict.pinned}\`, which is current against stable \`${verdict.latest.version}\`. Closing.${FOOTER}`
}

// ---------------------------------------------------------------------------
// Driving the tracker
// ---------------------------------------------------------------------------

/**
 * One pass. `api` is the tracker (see `githubApi`), everything else is text
 * already read, so a test can hand in fixtures and see exactly what the pass
 * would do to the tracker.
 *
 * @returns {{status, action: 'opened'|'commented'|'unchanged'|'closed'|'none', summary, verdict}}
 */
export async function runCheck(api, { buildYaml, pubspecLock, releases, dryRun = false }) {
  const verdict = assess({
    pinned: pinnedVersion(buildYaml),
    latest: latestStable(releases),
    floor: lockfileFloor(pubspecLock),
  })
  const open = await api.findOpenIssue(ISSUE_TITLE)
  const mark = marker(verdict.latest.version)

  let action
  if (verdict.status === 'current') {
    action = open ? 'closed' : 'none'
    if (open && !dryRun) await api.closeIssue(open.number, closingComment(verdict))
  } else if (!open) {
    action = 'opened'
    if (!dryRun) await api.createIssue(ISSUE_TITLE, issueBody(verdict), ISSUE_LABELS)
  } else if ((open.body ?? '').includes(mark)) {
    action = 'unchanged'
  } else {
    action = 'unchanged'
    if (dryRun) action = 'commented'
    else if (await api.commentOnce(open.number, mark, updateComment(verdict))) action = 'commented'
  }

  return {
    status: verdict.status,
    action,
    verdict,
    summary: summaryLine(verdict, action, open, dryRun),
  }
}

function summaryLine(verdict, action, open, dryRun) {
  const { pinned, latest, floor, status } = verdict
  const state =
    status === 'current'
      ? `Flutter pin ${pinned} is current (stable ${latest.version}).`
      : status === 'below-floor'
        ? `Flutter pin ${pinned} is below the pubspec.lock floor >=${floor}; stable is ${latest.version}.`
        : `Flutter pin ${pinned} is behind stable ${latest.version}${releasedOn(latest)}.`
  const did = {
    opened: 'Opened an issue.',
    commented: `Commented on #${open?.number}.`,
    unchanged: `#${open?.number} already says so.`,
    closed: `Closed #${open?.number}.`,
    none: 'Nothing open, nothing to do.',
  }[action]
  return `${state} ${dryRun ? `Dry run — would have: ${did}` : did}`
}

// ---------------------------------------------------------------------------
// The gh-backed tracker, and the entry point.
// ---------------------------------------------------------------------------

function gh(args) {
  const out = execFileSync('gh', args, {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
  })
  return out.trim() ? JSON.parse(out) : null
}

export function githubApi(repo) {
  return {
    /** The open issue with exactly this title, with its body and comment bodies, or null. */
    findOpenIssue: async (title) => {
      const found =
        gh([
          'api',
          `search/issues?q=${encodeURIComponent(`repo:${repo} is:issue is:open in:title "${title}"`)}&per_page=20`,
          '--jq',
          `[.items[] | select(.title == ${JSON.stringify(title)}) | {number, body}] | first // empty`,
        ]) ?? null
      if (!found) return null
      const comments =
        gh(['api', `repos/${repo}/issues/${found.number}/comments?per_page=100`, '--jq', '[.[].body]']) ?? []
      return { number: found.number, body: found.body ?? '', comments }
    },

    createIssue: async (title, body, labels) => {
      const created = gh([
        'api',
        '-X',
        'POST',
        `repos/${repo}/issues`,
        '-f',
        `title=${title}`,
        '-f',
        `body=${body}`,
        ...labels.flatMap((label) => ['-f', `labels[]=${label}`]),
      ])
      return created?.number ?? null
    },

    /** Say a thing once per stable release, so a weekly run is not a thread. */
    commentOnce: async (number, mark, body) => {
      const existing = gh(['api', `repos/${repo}/issues/${number}/comments?per_page=100`, '--jq', '[.[].body]']) ?? []
      if (existing.some((text) => text.includes(mark))) return false
      gh(['api', '-X', 'POST', `repos/${repo}/issues/${number}/comments`, '-f', `body=${body}\n\n${mark}`])
      return true
    },

    closeIssue: async (number, comment) => {
      gh(['api', '-X', 'POST', `repos/${repo}/issues/${number}/comments`, '-f', `body=${comment}`])
      gh(['api', '-X', 'PATCH', `repos/${repo}/issues/${number}`, '-f', 'state=closed', '-f', 'state_reason=completed'])
    },
  }
}

export async function fetchReleases(url = RELEASES_URL) {
  const response = await fetch(url, {
    headers: { accept: 'application/json' },
  })
  if (!response.ok) throw new Error(`${url} answered HTTP ${response.status}`)
  return response.json()
}

async function main() {
  const repo = process.env.GITHUB_REPOSITORY
  if (!repo) throw new Error('GITHUB_REPOSITORY is not set')

  const result = await runCheck(githubApi(repo), {
    buildYaml: readFileSync(BUILD_YAML, 'utf8'),
    pubspecLock: readFileSync(PUBSPEC_LOCK, 'utf8'),
    releases: await fetchReleases(process.env.FLUTTER_RELEASES_URL || RELEASES_URL),
    dryRun: process.env.DRY_RUN === 'true',
  })

  console.log(result.summary)
  if (process.env.GITHUB_STEP_SUMMARY) appendFileSync(process.env.GITHUB_STEP_SUMMARY, `${result.summary}\n`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(String(error?.stderr ?? error?.message ?? error).trim())
    process.exit(1)
  })
}
