<?php

/**
 * Club Bar Configuration
 *
 * Use the web installer — visit /install.php in your browser. It decides where
 * this file belongs: a directory above the document root where your hosting has
 * a writable one, `backend/config.php` where it does not (ADR-0031 decision 2).
 *
 * To write it by hand, copy it to the data directory named by `data-path.php`
 * in the document root, or to `backend/config.php` if that file does not exist.
 * Never leave a copy next to `index.php`: it holds the database password and
 * the TOTP encryption key, and one webserver misconfiguration away it is a
 * download.
 */
return [
    'db' => [
        'host' => 'localhost',
        'port' => 3306,
        'name' => 'clubbar',
        'user' => '',
        'pass' => '',
    ],
    'app' => [
        'env' => 'production',
        'debug' => false,
        'url' => 'https://example.com',
    ],
    'session' => [
        'max_age' => 7200,
        'regeneration_interval' => 900,
        // Where PHP writes session files. Left unset, the app uses
        // backend/storage/sessions rather than the host's shared session
        // directory, where another account on the machine may be able to read
        // them. Point this at a directory outside the document root if your
        // hosting offers one — it must be writable by the web server.
        // 'save_path' => '/home/user/clubbar-data/sessions',
    ],
    'api_token' => [
        // Terminal token lifetime. 365 days is the shared credential
        // cryptoperiod (ADR-0036); rotation stages the replacement alongside
        // the current token, so the deadline is not an outage (#395).
        'ttl_days' => 365,
    ],
    'security' => [
        // 64-char hex string (32 bytes). Generated automatically by install.php.
        // To regenerate manually: openssl rand -hex 32
        'totp_encryption_key' => '',
        // 64-char hex string (32 bytes). Keys the BLAKE2b fingerprint that lets
        // the app compare a submitted IBAN with a stored (sealed) one without
        // being able to decrypt it (ADR-0036). Generated by install.php and
        // backfilled by upgrade.php. Regenerating it on an existing install
        // breaks bank-change detection until every mandate is re-saved — treat
        // it like the TOTP key and leave it alone.
        'iban_fingerprint_key' => '',
    ],
    'mail' => [
        // One DSN selects the transport for outgoing mail (ADR-0038).
        // It holds an SMTP password, which is why it lives here next to the
        // database password rather than in the admin panel — everything about
        // a mail that is *not* secret (sender name, reply-to, footer) is
        // configured under Settings instead.
        //
        //   smtp://user:password@mail.example.org:587   the club's own mailbox
        //   native://default                            the host's local MTA
        //   null://null                                 configured, and discards
        //
        // Leave empty to disable mail. Nothing is sent, nothing throws, and the
        // security self-check reports the transport as unconfigured.
        //
        // Note that sending needs a scheduler as well: the announcement queue
        // is drained by cron and by nothing else. The installer shows the
        // command for this installation and verifies it has run.
        'dsn' => '',

        // How much one drain run does before it stops.
        //
        // **Both now live in the admin panel** — Settings → Mail — because
        // neither has a secret in it and the operator who needs to change one
        // is the least likely to be able to edit this file (#473). Set them
        // here only for a host that has to pin the value outside the database;
        // an entry here overrides the panel.
        //
        //   drain_batch_size      messages claimed per round (panel default 100)
        //   drain_budget_seconds  wall-clock budget for one run (panel default 25, max 55)
        //
        // Lower the budget if the panel's URL cron is cut off mid-run: the
        // limit that kills it is the host's gateway *read* timeout, which is
        // not max_execution_time and cannot be raised from PHP. Whatever a run
        // does not finish stays queued for the next tick.
        // 'drain_batch_size' => 25,
        // 'drain_budget_seconds' => 25,
    ],
    'cron' => [
        // Only needed on hosting with no CLI cron (ADR-0038 rule 3).
        //
        // The preferred scheduler runs the command directly, and needs nothing
        // here:
        //
        //   /usr/bin/php /path/to/htdocs/backend/bin/cron.php
        //
        // Where the panel can only fetch a URL, set a secret — 64 hex chars,
        // generated by the installer, or `openssl rand -hex 32` — and schedule:
        //
        //   curl -sS -H 'X-Cron-Secret: <secret>' https://example.com/api/cron/drain
        //
        // The header is the supported form. If the panel cannot send one, the
        // secret may go in the query string instead
        // (`…/api/cron/drain?secret=<secret>`) — but that is a **degraded**
        // setup: the request line, secret and all, is written verbatim to the
        // webserver's access log, where backups and log-shipping take it along.
        // Rotate it by changing this value; it takes effect on the next request
        // and nothing else depends on it.
        //
        // Leave empty and the URL route is not mounted at all: an installation
        // on a CLI cron carries no second, unauthenticated entrance.
        'secret' => '',

        // Where each drain run reports in, so somebody finds out when it stops
        // (#406). Strongly recommended: the queue is the only sending path, and
        // a scheduler that quietly dies erodes the seven-day announcement
        // promise without a single error anywhere in this application.
        //
        // Any push monitor with a check URL works — healthchecks.io,
        // Uptime Kuma, Cronitor, Better Stack. Paste the check's ping URL:
        //
        //   'heartbeat_url' => 'https://hc-ping.com/<uuid>',
        //
        // Each run pings <url>/start when it begins and <url> when it finishes;
        // an unusable transport or a queue that has been due for three ticks
        // pings <url>/fail. A single rejected address does not — it is recorded
        // on the message for the Kassenwart, and an alarm that fires on every
        // typo'd address gets switched off within weeks.
        //
        // Recommended check settings: period 1 day, grace 1–2 hours. The mail
        // is queued at finalize and the collection is at least seven days out,
        // so a one-day alarm still leaves six days to react — while a tighter
        // period would fire on every single missed tick.
        //
        // The ping body carries counts only: never an address, never a name.
        // Leave empty and nothing is pinged.
        'heartbeat_url' => '',
    ],

    // -------------------------------------------------------------------------
    // Encrypted off-site backups (ADR-0049)
    // -------------------------------------------------------------------------
    // Nothing here is filled in by the installer, because two of the four
    // values cannot be: the keypairs are generated on a laptop, and their
    // private halves must never reach this server.
    'backup' => [
        // WHO CAN OPEN AN ARCHIVE. A list of `label:public_key_hex`, one entry
        // per recipient, generated offline with tools/keypair-generator.html.
        //
        //   'public_keys' => [
        //       'admin:3d1f…',      // 64 hex characters
        //       'vorstand:9a02…',
        //   ],
        //
        // TWO ENTRIES, NOT ONE, and the reason is organisational rather than
        // cryptographic: the realistic failure in a Verein is "der Vorstand hat
        // gewechselt und niemand hat den Schlüssel". Each costs about 48 bytes
        // in every archive. One private half goes to the **Admin** — whoever
        // holds the server — and one to a second board member, archived like
        // the key to the safe.
        //
        // NOT TO THE KASSENWART, and not the IBAN keypair either. A backup
        // carries the audit log, every admin's TOTP ciphertext and the database
        // password; the Kassenwart holds the IBAN private key because SEPA
        // collection is impossible without it, and handing them a backup key
        // would re-cross that boundary through a different keypair.
        //
        // ROTATION IS ADDITIVE. Add the successor's key, let both open new
        // archives, prove the new one opens a real archive, then remove the
        // departing one. **Delete no archives**, and do not discard the retired
        // *private* key: "rotated" means dead for writing, not for reading, and
        // archives sealed to it exist until retention has drained (about four
        // months). The panel's key list is what says when nothing needs it.
        //
        // EMPTY MEANS NO BACKUP IS WRITTEN AT ALL. There is no plaintext
        // fallback — ADR-0031 rule 3: refuse and report, never silently
        // degrade. The security self-check reports it.
        'public_keys' => [],

        // Where finished archives are pushed. Empty means local-only: archives
        // are written to the data directory and pruned there, which satisfies
        // "undo a mistake an hour ago" and none of "the webspace is gone".
        //
        //   'dsn' => 'msgraph://<tenant-id>/<client-id>@<site>/<library>/<path>',
        //
        'dsn' => '',

        // The secret half of the DSN's credential, kept out of it for the same
        // reason the SMTP password is kept out of a URL that gets pasted into
        // support threads.
        'client_secret' => '',

        // A push monitor for the backup job, and deliberately NOT the mail one
        // (`cron.heartbeat_url` above). Turning a check that guards a legal
        // deadline red for a storage problem teaches the operator to ignore it.
        //
        // Recommended check settings: period 1 day, grace 6 hours — a nightly
        // job that misses one night is worth knowing about in the morning, not
        // at 03:05.
        //
        // The ping body carries counts and a closed set of reasons: never a
        // table name, never a filename, never a key.
        'heartbeat_url' => '',
    ],
];
