<?php

/**
 * Club Bar Configuration
 *
 * Use the web installer — visit /install.php in your browser. It decides where
 * this file belongs: a directory above the document root where your hosting has
 * a writable one, `backend/config.php` where it does not (ADR-0031 decision 2).
 *
 * To write it by hand, copy it to the data directory named by `data-path.php`
 * in the document root, or to `backend/config.php` if that file does not exist.
 * Never leave a copy next to `index.php`: it holds the database password and
 * the TOTP encryption key, and one webserver misconfiguration away it is a
 * download.
 */
return [
    'db' => [
        'host' => 'localhost',
        'port' => 3306,
        'name' => 'clubbar',
        'user' => '',
        'pass' => '',
    ],
    'app' => [
        'env' => 'production',
        'debug' => false,
        'url' => 'https://example.com',
    ],
    'session' => [
        'max_age' => 7200,
        'regeneration_interval' => 900,
        // Where PHP writes session files. Left unset, the app uses
        // backend/storage/sessions rather than the host's shared session
        // directory, where another account on the machine may be able to read
        // them. Point this at a directory outside the document root if your
        // hosting offers one — it must be writable by the web server.
        // 'save_path' => '/home/user/clubbar-data/sessions',
    ],
    'api_token' => [
        // Terminal token lifetime. 365 days is the shared credential
        // cryptoperiod (ADR-0036); rotation stages the replacement alongside
        // the current token, so the deadline is not an outage (#395).
        'ttl_days' => 365,
    ],
    'security' => [
        // 64-char hex string (32 bytes). Generated automatically by install.php.
        // To regenerate manually: openssl rand -hex 32
        'totp_encryption_key' => '',
        // 64-char hex string (32 bytes). Keys the BLAKE2b fingerprint that lets
        // the app compare a submitted IBAN with a stored (sealed) one without
        // being able to decrypt it (ADR-0036). Generated by install.php and
        // backfilled by upgrade.php. Regenerating it on an existing install
        // breaks bank-change detection until every mandate is re-saved — treat
        // it like the TOTP key and leave it alone.
        'iban_fingerprint_key' => '',
    ],
    'mail' => [
        // One DSN selects the transport for outgoing mail (ADR-0038).
        // It holds an SMTP password, which is why it lives here next to the
        // database password rather than in the admin panel — everything about
        // a mail that is *not* secret (sender name, reply-to, footer) is
        // configured under Settings instead.
        //
        //   smtp://user:password@mail.example.org:587   the club's own mailbox
        //   native://default                            the host's local MTA
        //   null://null                                 configured, and discards
        //
        // Leave empty to disable mail. Nothing is sent, nothing throws, and the
        // security self-check reports the transport as unconfigured.
        //
        // Note that sending needs a scheduler as well: the announcement queue
        // is drained by cron and by nothing else. The installer shows the
        // command for this installation and verifies it has run.
        'dsn' => '',

        // How much one drain run does before it stops. The defaults suit a
        // club-sized settlement and a typical shared host; both are here for
        // the tariff that differs.
        //
        //   drain_batch_size      messages claimed per round (default 25)
        //   drain_budget_seconds  wall-clock budget for one run (default 50)
        //
        // Lower the budget if the panel's URL cron is cut off mid-run: the
        // limit that kills it is the host's gateway *read* timeout, which is
        // not max_execution_time and cannot be raised from PHP. Whatever a run
        // does not finish stays queued for the next tick.
        // 'drain_batch_size' => 25,
        // 'drain_budget_seconds' => 50,
    ],
    'cron' => [
        // Only needed on hosting with no CLI cron (ADR-0038 rule 3).
        //
        // The preferred scheduler runs the command directly, and needs nothing
        // here:
        //
        //   /usr/bin/php /path/to/htdocs/backend/bin/cron.php
        //
        // Where the panel can only fetch a URL, set a secret — 64 hex chars,
        // generated by the installer, or `openssl rand -hex 32` — and schedule:
        //
        //   curl -sS -H 'X-Cron-Secret: <secret>' https://example.com/api/cron/drain
        //
        // The header is the supported form. If the panel cannot send one, the
        // secret may go in the query string instead
        // (`…/api/cron/drain?secret=<secret>`) — but that is a **degraded**
        // setup: the request line, secret and all, is written verbatim to the
        // webserver's access log, where backups and log-shipping take it along.
        // Rotate it by changing this value; it takes effect on the next request
        // and nothing else depends on it.
        //
        // Leave empty and the URL route is not mounted at all: an installation
        // on a CLI cron carries no second, unauthenticated entrance.
        'secret' => '',
    ],
    'llm' => [
        // Optional: enables AI-powered mandate document extraction.
        // Leave provider empty (or omit this section) to disable extraction silently.
        // Supported providers: 'anthropic', 'openai'
        'provider' => '',
        'api_key' => '',
        'model' => '',  // defaults: claude-haiku-4-5-20251001 (anthropic) / gpt-4o-mini (openai)
        'thinking_budget' => 0,
    ],
];
